// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RapidScada.Persistence;

#nullable disable

namespace RapidScada.Persistence.Migrations
{
    [DbContext(typeof(ScadaDbContext))]
    partial class ScadaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RapidScada.Domain.Entities.CommunicationLine", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel_type");

                    b.Property<string>("ConnectionSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("connection_settings");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ChannelType")
                        .HasDatabaseName("idx_communication_lines_channel_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_communication_lines_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_communication_lines_name");

                    b.ToTable("communication_lines", (string)null);
                });

            modelBuilder.Entity("RapidScada.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Address")
                        .HasColumnType("integer")
                        .HasColumnName("address");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("call_sign");

                    b.Property<int>("CommunicationLineId")
                        .HasColumnType("integer")
                        .HasColumnName("communication_line_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("device_type_id");

                    b.Property<DateTime?>("LastCommunicationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_communication_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationLineId")
                        .HasDatabaseName("idx_devices_communication_line_id");

                    b.HasIndex("LastCommunicationAt")
                        .HasDatabaseName("idx_devices_last_communication_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_devices_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_devices_status");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("RapidScada.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("current_value");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("Formula")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("formula");

                    b.Property<double?>("HighLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("high_limit");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_at");

                    b.Property<double?>("LowLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("low_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tag_type");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdateAt")
                        .HasDatabaseName("idx_tags_last_update_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tags_status");

                    b.HasIndex("DeviceId", "Number")
                        .IsUnique()
                        .HasDatabaseName("idx_tags_device_id_number");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("RapidScada.Domain.Entities.Device", b =>
                {
                    b.HasOne("RapidScada.Domain.Entities.CommunicationLine", null)
                        .WithMany()
                        .HasForeignKey("CommunicationLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RapidScada.Domain.Entities.Tag", b =>
                {
                    b.HasOne("RapidScada.Domain.Entities.Device", null)
                        .WithMany("Tags")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapidScada.Domain.Entities.Device", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
